defaultSemverRangePrefix: ^

packageExtensions:
  "@samverschueren/stream-to-observable@*":
    peerDependenciesMeta:
      rxjs:
        optional: true
      zen-observable:
        optional: true
  any-observable@*:
    peerDependenciesMeta:
      rxjs:
        optional: true
      zen-observable:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-deduplicate.cjs
    spec: "https://raw.githubusercontent.com/eps1lon/yarn-plugin-deduplicate/latest/bin/%40yarnpkg/plugin-deduplicate.js"

yarnPath: .yarn/releases/yarn-2.2.2.cjs
