defaultSemverRangePrefix: ^

packageExtensions:
  "@samverschueren/stream-to-observable@*":
    peerDependenciesMeta:
      rxjs:
        optional: true
      zen-observable:
        optional: true
  any-observable@*:
    peerDependenciesMeta:
      rxjs:
        optional: true
      zen-observable:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-rc.js
